###
GET http://localhost:3001/api/v1/korkeusmalli2m

### asd
POST http://localhost:3001/api/v1/korkeusmalli2m
content-type: application/json

{
    "latitude": 62.60991053905554, 
    "longitude": 29.789833160383374
}